"""Second Migration

Revision ID: 49bea708dc42
Revises: 2263ca06d02e
Create Date: 2024-04-15 09:39:50.086740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49bea708dc42'
down_revision = '2263ca06d02e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_communications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=300), nullable=True))
        batch_op.create_index(batch_op.f('ix_post_communications_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('post_contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=30), nullable=True))
        batch_op.create_index(batch_op.f('ix_post_contents_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_contents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_contents_title'))
        batch_op.drop_column('title')

    with op.batch_alter_table('post_communications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_communications_user_id'))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
