"""Post_contents migration

Revision ID: a26b2b13c59f
Revises: 49bea708dc42
Create Date: 2024-04-21 15:15:43.824247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a26b2b13c59f'
down_revision = '49bea708dc42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_contents', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_contents', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
