"""Initial migration

Revision ID: ddb46d8e5992
Revises: 
Create Date: 2024-03-24 23:42:32.356148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddb46d8e5992'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_communications',
    sa.Column('post_id', sa.String(length=300), nullable=False),
    sa.Column('replyed_by', sa.String(length=300), nullable=True),
    sa.Column('reply_no', sa.Integer(), nullable=True),
    sa.Column('reply_text', sa.String(length=300), nullable=True),
    sa.Column('reply_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('post_contents',
    sa.Column('user_id', sa.String(length=300), nullable=True),
    sa.Column('post_id', sa.String(length=300), nullable=False),
    sa.Column('image_url', sa.String(length=300), nullable=True),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('good_no', sa.Integer(), nullable=True),
    sa.Column('post_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('post_id')
    )
    with op.batch_alter_table('post_contents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_contents_user_id'), ['user_id'], unique=False)

    op.create_table('relations',
    sa.Column('relarion_id', sa.Integer(), nullable=False),
    sa.Column('followed_by', sa.String(length=300), nullable=True),
    sa.Column('follow_to', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('relarion_id')
    )
    with op.batch_alter_table('relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relations_follow_to'), ['follow_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_relations_followed_by'), ['followed_by'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=300), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_nickname'), ['nickname'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_nickname'))

    op.drop_table('users')
    with op.batch_alter_table('relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relations_followed_by'))
        batch_op.drop_index(batch_op.f('ix_relations_follow_to'))

    op.drop_table('relations')
    with op.batch_alter_table('post_contents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_contents_user_id'))

    op.drop_table('post_contents')
    op.drop_table('post_communications')
    # ### end Alembic commands ###
